/* This file was generated by SableCC (http://www.sablecc.org/). */

using System;
using System.Collections;
using System.Text;
using System.IO;
using comp5210.node;

namespace comp5210.lexer {

internal class PushbackReader {
  private TextReader reader;
  private Stack stack = new Stack ();


  internal PushbackReader (TextReader reader)
  {
    this.reader = reader;
  }

  internal int Peek ()
  {
    if ( stack.Count > 0 ) return (int)stack.Peek();
    return reader.Peek();
  }

  internal int Read ()
  {
    if ( stack.Count > 0 ) return (int)stack.Pop();
    return reader.Read();
  }

  internal void Unread (int v)
  {
    stack.Push (v);
  }
}

public class LexerException : ApplicationException
{
    public LexerException(String message) : base (message)
    {
    }
}

public class Lexer
{
    protected Token token;
    protected State currentState = State.INITIAL;

    private PushbackReader input;
    private int line;
    private int pos;
    private bool cr;
    private bool eof;
    private StringBuilder text = new StringBuilder();

    protected virtual void Filter()
    {
    }

    public Lexer(TextReader input)
    {
        this.input = new PushbackReader(input);
    }

    public virtual Token Peek()
    {
        while(token == null)
        {
            token = GetToken();
            Filter();
        }

        return token;
    }

    public virtual Token Next()
    {
        while(token == null)
        {
            token = GetToken();
            Filter();
        }

        Token result = token;
        token = null;
        return result;
    }

    protected virtual Token GetToken()
    {
        int dfa_state = 0;

        int start_pos = pos;
        int start_line = line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        int[][][] gotoTable = Lexer.gotoTable[currentState.id()];
        int[] accept = Lexer.accept[currentState.id()];
        text.Length = 0;

        while(true)
        {
            int c = GetChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(cr)
                    {
                        cr = false;
                    }
                    else
                    {
                        line++;
                        pos = 0;
                    }
                    break;
                case 13:
                    line++;
                    pos = 0;
                    cr = true;
                    break;
                default:
                    pos++;
                    cr = false;
                    break;
                };

                text.Append((char) c);
                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.Length - 1;

                    while(low <= high)
                    {
                        int middle = (low + high) / 2;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = text.Length;
                    accept_pos = pos;
                    accept_line = line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            Token token = New0(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            Token token = New1(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            Token token = New2(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            Token token = New3(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            Token token = New4(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            Token token = New5(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            Token token = New6(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            Token token = New7(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            Token token = New8(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            Token token = New9(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            Token token = New10(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            Token token = New11(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            Token token = New12(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            Token token = New13(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            Token token = New14(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            Token token = New15(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            Token token = New16(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            Token token = New17(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            Token token = New18(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            Token token = New19(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            Token token = New20(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            Token token = New21(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            Token token = New22(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            Token token = New23(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            Token token = New24(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            Token token = New25(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            Token token = New26(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            Token token = New27(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            Token token = New28(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            Token token = New29(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            Token token = New30(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            Token token = New31(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            Token token = New32(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            Token token = New33(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            Token token = New34(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            Token token = New35(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            Token token = New36(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            Token token = New37(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(text.Length > 0)
                    {
                        throw new LexerException(
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + text);
                    }
                    else
                    {
                        EOF token = new EOF(
                            start_line + 1,
                            start_pos + 1);
                        return token;
                    }
                }
            }
        }
    }

    private Token New0(String text, int line, int pos) { return new TIf(text, line, pos); }
    private Token New1(String text, int line, int pos) { return new TElse(text, line, pos); }
    private Token New2(String text, int line, int pos) { return new TWhile(text, line, pos); }
    private Token New3(String text, int line, int pos) { return new TMethod(text, line, pos); }
    private Token New4(String text, int line, int pos) { return new TReturn(text, line, pos); }
    private Token New5(String text, int line, int pos) { return new TConstant(text, line, pos); }
    private Token New6(String text, int line, int pos) { return new TVariable(text, line, pos); }
    private Token New7(String text, int line, int pos) { return new TWhitespace(text, line, pos); }
    private Token New8(String text, int line, int pos) { return new TComment(text, line, pos); }
    private Token New9(String text, int line, int pos) { return new TInteger(text, line, pos); }
    private Token New10(String text, int line, int pos) { return new TFloat(text, line, pos); }
    private Token New11(String text, int line, int pos) { return new TString(text, line, pos); }
    private Token New12(String text, int line, int pos) { return new TAdd(text, line, pos); }
    private Token New13(String text, int line, int pos) { return new TSubtract(text, line, pos); }
    private Token New14(String text, int line, int pos) { return new TMultiply(text, line, pos); }
    private Token New15(String text, int line, int pos) { return new TDivide(text, line, pos); }
    private Token New16(String text, int line, int pos) { return new TAnd(text, line, pos); }
    private Token New17(String text, int line, int pos) { return new TOr(text, line, pos); }
    private Token New18(String text, int line, int pos) { return new TNot(text, line, pos); }
    private Token New19(String text, int line, int pos) { return new TEquals(text, line, pos); }
    private Token New20(String text, int line, int pos) { return new TCompareEquals(text, line, pos); }
    private Token New21(String text, int line, int pos) { return new TGreaterEquals(text, line, pos); }
    private Token New22(String text, int line, int pos) { return new TLesserEquals(text, line, pos); }
    private Token New23(String text, int line, int pos) { return new TGreaterThan(text, line, pos); }
    private Token New24(String text, int line, int pos) { return new TLessThan(text, line, pos); }
    private Token New25(String text, int line, int pos) { return new TLparen(text, line, pos); }
    private Token New26(String text, int line, int pos) { return new TRparen(text, line, pos); }
    private Token New27(String text, int line, int pos) { return new TLbrace(text, line, pos); }
    private Token New28(String text, int line, int pos) { return new TRbrace(text, line, pos); }
    private Token New29(String text, int line, int pos) { return new TLbracket(text, line, pos); }
    private Token New30(String text, int line, int pos) { return new TRbracket(text, line, pos); }
    private Token New31(String text, int line, int pos) { return new TSemicolon(text, line, pos); }
    private Token New32(String text, int line, int pos) { return new TColon(text, line, pos); }
    private Token New33(String text, int line, int pos) { return new TPeriod(text, line, pos); }
    private Token New34(String text, int line, int pos) { return new TComma(text, line, pos); }
    private Token New35(String text, int line, int pos) { return new TUnderscore(text, line, pos); }
    private Token New36(String text, int line, int pos) { return new TDoublequote(text, line, pos); }
    private Token New37(String text, int line, int pos) { return new TLetters(text, line, pos); }

    private int GetChar()
    {
        if(eof)
        {
            return -1;
        }

        int result = input.Read();

        if(result == -1)
        {
            eof = true;
        }

        return result;
    }

    private void PushBack(int acceptLength)
    {
        int length = text.Length;
        for(int i = length - 1; i >= acceptLength; i--)
        {
            eof = false;

            input.Unread(text[i]);
        }
    }


    protected virtual void Unread(Token token)
    {
        String text = token.Text;
        int length = text.Length;

        for(int i = length - 1; i >= 0; i--)
        {
            eof = false;

            input.Unread(text[i]);
        }

        pos = token.Pos - 1;
        line = token.Line - 1;
    }

    private string GetText(int acceptLength)
    {
        StringBuilder s = new StringBuilder(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.Append(text[i]);
        }

        return s.ToString();
    }

    private static int[][][][] gotoTable = {
      new int[][][] {
        new int[][] {
          new int[] {9, 9, 1},
          new int[] {10, 10, 2},
          new int[] {13, 13, 3},
          new int[] {32, 32, 4},
          new int[] {33, 33, 5},
          new int[] {34, 34, 6},
          new int[] {38, 38, 7},
          new int[] {40, 40, 8},
          new int[] {41, 41, 9},
          new int[] {42, 42, 10},
          new int[] {43, 43, 11},
          new int[] {44, 44, 12},
          new int[] {45, 45, 13},
          new int[] {46, 46, 14},
          new int[] {47, 47, 15},
          new int[] {48, 57, 16},
          new int[] {58, 58, 17},
          new int[] {59, 59, 18},
          new int[] {60, 60, 19},
          new int[] {61, 61, 20},
          new int[] {62, 62, 21},
          new int[] {65, 65, 22},
          new int[] {66, 67, 23},
          new int[] {68, 68, 24},
          new int[] {69, 69, 25},
          new int[] {70, 72, 23},
          new int[] {73, 73, 26},
          new int[] {74, 76, 23},
          new int[] {77, 77, 27},
          new int[] {78, 78, 28},
          new int[] {79, 79, 29},
          new int[] {80, 82, 23},
          new int[] {83, 83, 30},
          new int[] {84, 90, 23},
          new int[] {91, 91, 31},
          new int[] {93, 93, 32},
          new int[] {95, 95, 33},
          new int[] {97, 98, 23},
          new int[] {99, 99, 34},
          new int[] {100, 100, 23},
          new int[] {101, 101, 35},
          new int[] {102, 104, 23},
          new int[] {105, 105, 36},
          new int[] {106, 108, 23},
          new int[] {109, 109, 37},
          new int[] {110, 113, 23},
          new int[] {114, 114, 38},
          new int[] {115, 117, 23},
          new int[] {118, 118, 39},
          new int[] {119, 119, 40},
          new int[] {120, 122, 23},
          new int[] {123, 123, 41},
          new int[] {124, 124, 42},
          new int[] {125, 125, 43},
        },
        new int[][] {
          new int[] {9, 32, -2},
        },
        new int[][] {
          new int[] {9, 32, -2},
        },
        new int[][] {
          new int[] {9, 32, -2},
        },
        new int[][] {
          new int[] {9, 32, -2},
        },
        new int[][] {
        },
        new int[][] {
          new int[] {32, 33, 44},
          new int[] {34, 34, 45},
          new int[] {35, 91, 46},
          new int[] {92, 92, 47},
          new int[] {93, 126, 48},
        },
        new int[][] {
          new int[] {38, 38, 49},
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
          new int[] {48, 57, 16},
        },
        new int[][] {
        },
        new int[][] {
          new int[] {42, 42, 50},
          new int[] {47, 47, 51},
        },
        new int[][] {
          new int[] {46, 46, 52},
          new int[] {48, 57, 16},
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
          new int[] {61, 61, 53},
        },
        new int[][] {
          new int[] {61, 61, 54},
        },
        new int[][] {
          new int[] {61, 61, 55},
        },
        new int[][] {
          new int[] {65, 67, 23},
          new int[] {68, 68, 56},
          new int[] {69, 77, 23},
          new int[] {78, 78, 57},
          new int[] {79, 90, 23},
          new int[] {97, 122, 23},
        },
        new int[][] {
          new int[] {65, 90, 23},
          new int[] {97, 122, 23},
        },
        new int[][] {
          new int[] {65, 72, 23},
          new int[] {73, 73, 58},
          new int[] {74, 90, 23},
          new int[] {97, 122, 23},
        },
        new int[][] {
          new int[] {65, 80, 23},
          new int[] {81, 81, 59},
          new int[] {82, 90, 23},
          new int[] {97, 122, 23},
        },
        new int[][] {
          new int[] {65, 82, 23},
          new int[] {83, 83, 60},
          new int[] {84, 90, 23},
          new int[] {97, 122, 23},
        },
        new int[][] {
          new int[] {65, 84, 23},
          new int[] {85, 85, 61},
          new int[] {86, 90, 23},
          new int[] {97, 122, 23},
        },
        new int[][] {
          new int[] {65, 78, 23},
          new int[] {79, 79, 62},
          new int[] {80, 90, 23},
          new int[] {97, 122, 23},
        },
        new int[][] {
          new int[] {65, 81, 23},
          new int[] {82, 82, 63},
          new int[] {83, 90, 23},
          new int[] {97, 122, 23},
        },
        new int[][] {
          new int[] {65, 84, 23},
          new int[] {85, 85, 64},
          new int[] {86, 122, -29},
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
          new int[] {65, 90, 23},
          new int[] {97, 110, 23},
          new int[] {111, 111, 65},
          new int[] {112, 122, 23},
        },
        new int[][] {
          new int[] {65, 90, 23},
          new int[] {97, 107, 23},
          new int[] {108, 108, 66},
          new int[] {109, 122, 23},
        },
        new int[][] {
          new int[] {65, 90, 23},
          new int[] {97, 101, 23},
          new int[] {102, 102, 67},
          new int[] {103, 122, 23},
        },
        new int[][] {
          new int[] {65, 90, 23},
          new int[] {97, 100, 23},
          new int[] {101, 101, 68},
          new int[] {102, 122, 23},
        },
        new int[][] {
          new int[] {65, 100, -39},
          new int[] {101, 101, 69},
          new int[] {102, 122, 23},
        },
        new int[][] {
          new int[] {65, 90, 23},
          new int[] {97, 97, 70},
          new int[] {98, 122, 23},
        },
        new int[][] {
          new int[] {65, 90, 23},
          new int[] {97, 103, 23},
          new int[] {104, 104, 71},
          new int[] {105, 122, 23},
        },
        new int[][] {
        },
        new int[][] {
          new int[] {124, 124, 72},
        },
        new int[][] {
        },
        new int[][] {
          new int[] {32, 126, -8},
        },
        new int[][] {
        },
        new int[][] {
          new int[] {32, 126, -8},
        },
        new int[][] {
          new int[] {34, 34, 73},
        },
        new int[][] {
          new int[] {32, 126, -8},
        },
        new int[][] {
        },
        new int[][] {
          new int[] {32, 41, 74},
          new int[] {42, 42, 75},
          new int[] {43, 127, 74},
        },
        new int[][] {
          new int[] {10, 10, 76},
          new int[] {13, 13, 77},
          new int[] {32, 127, 78},
        },
        new int[][] {
          new int[] {48, 57, 79},
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
          new int[] {65, 67, 23},
          new int[] {68, 68, 80},
          new int[] {69, 90, 23},
          new int[] {97, 122, 23},
        },
        new int[][] {
          new int[] {65, 67, 23},
          new int[] {68, 68, 81},
          new int[] {69, 122, -58},
        },
        new int[][] {
          new int[] {65, 85, 23},
          new int[] {86, 86, 82},
          new int[] {87, 90, 23},
          new int[] {97, 122, 23},
        },
        new int[][] {
          new int[] {65, 84, 23},
          new int[] {85, 85, 83},
          new int[] {86, 122, -29},
        },
        new int[][] {
          new int[] {65, 68, 23},
          new int[] {69, 69, 84},
          new int[] {70, 70, 23},
          new int[] {71, 71, 85},
          new int[] {72, 75, 23},
          new int[] {76, 76, 86},
          new int[] {77, 90, 23},
          new int[] {97, 122, 23},
        },
        new int[][] {
          new int[] {65, 75, 23},
          new int[] {76, 76, 87},
          new int[] {77, 122, -62},
        },
        new int[][] {
          new int[] {65, 83, 23},
          new int[] {84, 84, 88},
          new int[] {85, 90, 23},
          new int[] {97, 122, 23},
        },
        new int[][] {
          new int[] {65, 122, -25},
        },
        new int[][] {
          new int[] {65, 65, 23},
          new int[] {66, 66, 89},
          new int[] {67, 90, 23},
          new int[] {97, 122, 23},
        },
        new int[][] {
          new int[] {65, 90, 23},
          new int[] {97, 109, 23},
          new int[] {110, 110, 90},
          new int[] {111, 122, 23},
        },
        new int[][] {
          new int[] {65, 90, 23},
          new int[] {97, 114, 23},
          new int[] {115, 115, 91},
          new int[] {116, 122, 23},
        },
        new int[][] {
          new int[] {65, 122, -25},
        },
        new int[][] {
          new int[] {65, 90, 23},
          new int[] {97, 115, 23},
          new int[] {116, 116, 92},
          new int[] {117, 122, 23},
        },
        new int[][] {
          new int[] {65, 115, -70},
          new int[] {116, 116, 93},
          new int[] {117, 122, 23},
        },
        new int[][] {
          new int[] {65, 90, 23},
          new int[] {97, 113, 23},
          new int[] {114, 114, 94},
          new int[] {115, 122, 23},
        },
        new int[][] {
          new int[] {65, 90, 23},
          new int[] {97, 104, 23},
          new int[] {105, 105, 95},
          new int[] {106, 122, 23},
        },
        new int[][] {
        },
        new int[][] {
          new int[] {32, 126, -8},
        },
        new int[][] {
          new int[] {32, 127, -52},
        },
        new int[][] {
          new int[] {32, 42, -52},
          new int[] {43, 46, 74},
          new int[] {47, 47, 96},
          new int[] {48, 127, 74},
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
          new int[] {10, 127, -53},
        },
        new int[][] {
          new int[] {45, 45, 97},
          new int[] {48, 57, 98},
          new int[] {101, 101, 99},
        },
        new int[][] {
          new int[] {65, 122, -25},
        },
        new int[][] {
          new int[] {65, 122, -25},
        },
        new int[][] {
          new int[] {65, 122, -25},
        },
        new int[][] {
          new int[] {65, 65, 100},
          new int[] {66, 90, 23},
          new int[] {97, 122, 23},
        },
        new int[][] {
          new int[] {65, 80, 23},
          new int[] {81, 81, 101},
          new int[] {82, 122, -27},
        },
        new int[][] {
          new int[] {65, 81, 23},
          new int[] {82, 82, 102},
          new int[] {83, 122, -31},
        },
        new int[][] {
          new int[] {65, 68, 23},
          new int[] {69, 69, 103},
          new int[] {70, 90, 23},
          new int[] {97, 122, 23},
        },
        new int[][] {
          new int[] {65, 83, 23},
          new int[] {84, 84, 104},
          new int[] {85, 122, -64},
        },
        new int[][] {
          new int[] {65, 122, -25},
        },
        new int[][] {
          new int[] {65, 122, -25},
        },
        new int[][] {
          new int[] {65, 114, -68},
          new int[] {115, 115, 105},
          new int[] {116, 122, 23},
        },
        new int[][] {
          new int[] {65, 100, -39},
          new int[] {101, 101, 106},
          new int[] {102, 122, 23},
        },
        new int[][] {
          new int[] {65, 103, -42},
          new int[] {104, 104, 107},
          new int[] {105, 122, 23},
        },
        new int[][] {
          new int[] {65, 90, 23},
          new int[] {97, 116, 23},
          new int[] {117, 117, 108},
          new int[] {118, 122, 23},
        },
        new int[][] {
          new int[] {32, 32, 109},
          new int[] {65, 122, -25},
        },
        new int[][] {
          new int[] {65, 107, -37},
          new int[] {108, 108, 110},
          new int[] {109, 122, 23},
        },
        new int[][] {
          new int[] {32, 127, -52},
        },
        new int[][] {
          new int[] {48, 57, 111},
        },
        new int[][] {
          new int[] {45, 101, -81},
        },
        new int[][] {
          new int[] {45, 45, 97},
          new int[] {48, 57, 111},
        },
        new int[][] {
          new int[] {65, 75, 23},
          new int[] {76, 76, 112},
          new int[] {77, 122, -62},
        },
        new int[][] {
          new int[] {65, 84, 23},
          new int[] {85, 85, 113},
          new int[] {86, 122, -29},
        },
        new int[][] {
          new int[] {65, 68, 23},
          new int[] {69, 69, 114},
          new int[] {70, 122, -88},
        },
        new int[][] {
          new int[] {65, 82, 23},
          new int[] {83, 83, 115},
          new int[] {84, 122, -28},
        },
        new int[][] {
          new int[] {65, 122, -25},
        },
        new int[][] {
          new int[] {65, 115, -70},
          new int[] {116, 116, 116},
          new int[] {117, 122, 23},
        },
        new int[][] {
          new int[] {65, 122, -25},
        },
        new int[][] {
          new int[] {65, 110, -36},
          new int[] {111, 111, 117},
          new int[] {112, 122, 23},
        },
        new int[][] {
          new int[] {65, 113, -72},
          new int[] {114, 114, 118},
          new int[] {115, 122, 23},
        },
        new int[][] {
          new int[] {65, 90, 119},
          new int[] {97, 122, 119},
        },
        new int[][] {
          new int[] {65, 100, -39},
          new int[] {101, 101, 120},
          new int[] {102, 122, 23},
        },
        new int[][] {
          new int[] {48, 57, 111},
        },
        new int[][] {
          new int[] {65, 82, 23},
          new int[] {83, 83, 121},
          new int[] {84, 122, -28},
        },
        new int[][] {
          new int[] {65, 65, 122},
          new int[] {66, 122, -85},
        },
        new int[][] {
          new int[] {65, 65, 123},
          new int[] {66, 122, -85},
        },
        new int[][] {
          new int[] {65, 82, 23},
          new int[] {83, 83, 124},
          new int[] {84, 122, -28},
        },
        new int[][] {
          new int[] {32, 32, 125},
          new int[] {65, 122, -25},
        },
        new int[][] {
          new int[] {65, 90, 23},
          new int[] {97, 99, 23},
          new int[] {100, 100, 126},
          new int[] {101, 122, 23},
        },
        new int[][] {
          new int[] {65, 109, -67},
          new int[] {110, 110, 127},
          new int[] {111, 122, 23},
        },
        new int[][] {
          new int[] {48, 57, 128},
          new int[] {65, 122, -111},
        },
        new int[][] {
          new int[] {65, 122, -25},
        },
        new int[][] {
          new int[] {65, 122, -25},
        },
        new int[][] {
          new int[] {65, 75, 23},
          new int[] {76, 76, 129},
          new int[] {77, 122, -62},
        },
        new int[][] {
          new int[] {65, 83, 23},
          new int[] {84, 84, 130},
          new int[] {85, 122, -64},
        },
        new int[][] {
          new int[] {65, 68, 23},
          new int[] {69, 69, 131},
          new int[] {70, 122, -88},
        },
        new int[][] {
          new int[] {65, 90, 132},
          new int[] {97, 122, 132},
        },
        new int[][] {
          new int[] {65, 122, -25},
        },
        new int[][] {
          new int[] {65, 122, -25},
        },
        new int[][] {
          new int[] {48, 57, 128},
        },
        new int[][] {
          new int[] {65, 122, -25},
        },
        new int[][] {
          new int[] {65, 68, 23},
          new int[] {69, 69, 133},
          new int[] {70, 122, -88},
        },
        new int[][] {
          new int[] {65, 81, 23},
          new int[] {82, 82, 134},
          new int[] {83, 122, -31},
        },
        new int[][] {
          new int[] {48, 57, 135},
          new int[] {65, 122, -127},
        },
        new int[][] {
          new int[] {65, 81, 23},
          new int[] {82, 82, 136},
          new int[] {83, 122, -31},
        },
        new int[][] {
          new int[] {65, 68, 23},
          new int[] {69, 69, 137},
          new int[] {70, 122, -88},
        },
        new int[][] {
          new int[] {48, 57, 135},
        },
        new int[][] {
          new int[] {65, 68, 23},
          new int[] {69, 69, 138},
          new int[] {70, 122, -88},
        },
        new int[][] {
          new int[] {65, 80, 23},
          new int[] {81, 81, 139},
          new int[] {82, 122, -27},
        },
        new int[][] {
          new int[] {65, 80, 23},
          new int[] {81, 81, 140},
          new int[] {82, 122, -27},
        },
        new int[][] {
          new int[] {65, 84, 23},
          new int[] {85, 85, 141},
          new int[] {86, 122, -29},
        },
        new int[][] {
          new int[] {65, 84, 23},
          new int[] {85, 85, 142},
          new int[] {86, 122, -29},
        },
        new int[][] {
          new int[] {65, 65, 143},
          new int[] {66, 122, -85},
        },
        new int[][] {
          new int[] {65, 65, 144},
          new int[] {66, 122, -85},
        },
        new int[][] {
          new int[] {65, 75, 23},
          new int[] {76, 76, 145},
          new int[] {77, 122, -62},
        },
        new int[][] {
          new int[] {65, 75, 23},
          new int[] {76, 76, 146},
          new int[] {77, 122, -62},
        },
        new int[][] {
          new int[] {65, 82, 23},
          new int[] {83, 83, 147},
          new int[] {84, 122, -28},
        },
        new int[][] {
          new int[] {65, 82, 23},
          new int[] {83, 83, 148},
          new int[] {84, 122, -28},
        },
        new int[][] {
          new int[] {65, 122, -25},
        },
        new int[][] {
          new int[] {65, 122, -25},
        },
      },
    };

    private static int[][] accept = {
      new int[] {
        -1, 7, 7, 7, 7, 18, 36, -1, 25, 26, 14, 12, 34, 13, 33, 15, 
        9, 32, 31, 24, 19, 23, 37, 37, 37, 37, 37, 37, 37, 37, 37, 29, 
        30, 35, 37, 37, 37, 37, 37, 37, 37, 27, -1, 28, -1, 11, -1, -1, 
        -1, 16, -1, -1, -1, 22, 20, 21, 37, 37, 37, 37, 37, 37, 37, 17, 
        37, 37, 37, 0, 37, 37, 37, 37, 17, -1, -1, -1, 8, 8, -1, 10, 
        12, 16, 15, 37, 37, 37, 37, 37, 18, 13, 37, 37, 37, 37, 37, 37, 
        8, -1, 10, -1, 37, 37, 37, 37, 14, 37, 1, 37, 37, -1, 37, 10, 
        37, 37, 37, 37, 37, 37, 37, 6, 2, 19, 37, 37, 37, -1, 3, 4, 
        6, 20, 37, 37, 5, 37, 24, 5, 23, 37, 37, 37, 37, 37, 37, 37, 
        37, 37, 37, 22, 21, 
      },
    };

    public class State
    {
        public static State INITIAL = new State(0);

        private int _id;

        private State(int _id)
        {
            this._id = _id;
        }

        public int id()
        {
            return _id;
        }
    }
}
}
