/* This file was generated by SableCC (http://www.sablecc.org/). */

using System;
using System.Collections;
using System.Text;
using System.IO;
using comp5210.node;
using comp5210.lexer;
using comp5210.analysis;

namespace comp5210.parser {

public class ParserException : ApplicationException
{
    Token token;

    public ParserException(Token token, String  message) : base(message)
    {
        this.token = token;
    }

    public Token Token
    {
      get { return token; }
    }
}

internal class State
{
    internal int state;
    internal ArrayList nodes;

    internal State(int state, ArrayList nodes)
    {
        this.state = state;
        this.nodes = nodes;
    }
}

internal class TokenIndex : AnalysisAdapter
{
    internal int index;

    public override void CaseTIf(TIf node)
    {
        index = 0;
    }

    public override void CaseTElse(TElse node)
    {
        index = 1;
    }

    public override void CaseTWhile(TWhile node)
    {
        index = 2;
    }

    public override void CaseTMethod(TMethod node)
    {
        index = 3;
    }

    public override void CaseTReturn(TReturn node)
    {
        index = 4;
    }

    public override void CaseTConstant(TConstant node)
    {
        index = 5;
    }

    public override void CaseTVariable(TVariable node)
    {
        index = 6;
    }

    public override void CaseTInteger(TInteger node)
    {
        index = 7;
    }

    public override void CaseTFloat(TFloat node)
    {
        index = 8;
    }

    public override void CaseTString(TString node)
    {
        index = 9;
    }

    public override void CaseTAdd(TAdd node)
    {
        index = 10;
    }

    public override void CaseTSubtract(TSubtract node)
    {
        index = 11;
    }

    public override void CaseTMultiply(TMultiply node)
    {
        index = 12;
    }

    public override void CaseTDivide(TDivide node)
    {
        index = 13;
    }

    public override void CaseTAnd(TAnd node)
    {
        index = 14;
    }

    public override void CaseTOr(TOr node)
    {
        index = 15;
    }

    public override void CaseTNot(TNot node)
    {
        index = 16;
    }

    public override void CaseTEquals(TEquals node)
    {
        index = 17;
    }

    public override void CaseTCompareEquals(TCompareEquals node)
    {
        index = 18;
    }

    public override void CaseTGreaterEquals(TGreaterEquals node)
    {
        index = 19;
    }

    public override void CaseTLesserEquals(TLesserEquals node)
    {
        index = 20;
    }

    public override void CaseTGreaterThan(TGreaterThan node)
    {
        index = 21;
    }

    public override void CaseTLessThan(TLessThan node)
    {
        index = 22;
    }

    public override void CaseTLparen(TLparen node)
    {
        index = 23;
    }

    public override void CaseTRparen(TRparen node)
    {
        index = 24;
    }

    public override void CaseTLbrace(TLbrace node)
    {
        index = 25;
    }

    public override void CaseTRbrace(TRbrace node)
    {
        index = 26;
    }

    public override void CaseTLbracket(TLbracket node)
    {
        index = 27;
    }

    public override void CaseTRbracket(TRbracket node)
    {
        index = 28;
    }

    public override void CaseTSemicolon(TSemicolon node)
    {
        index = 29;
    }

    public override void CaseTColon(TColon node)
    {
        index = 30;
    }

    public override void CaseTPeriod(TPeriod node)
    {
        index = 31;
    }

    public override void CaseTComma(TComma node)
    {
        index = 32;
    }

    public override void CaseTUnderscore(TUnderscore node)
    {
        index = 33;
    }

    public override void CaseTDoublequote(TDoublequote node)
    {
        index = 34;
    }

    public override void CaseTLetters(TLetters node)
    {
        index = 35;
    }

    public override void CaseEOF(EOF node)
    {
        index = 36;
    }
}

public class Parser
{
    private Analysis ignoredTokens = new AnalysisAdapter();
    public Analysis IgnoredTokens
    {
      get { return ignoredTokens; }
    }

    protected ArrayList nodeList;

    private Lexer lexer;
    private Stack stack = new Stack();
    private int last_shift;
    private int last_pos;
    private int last_line;
    private Token last_token;
    private TokenIndex converter = new TokenIndex();
    private int[] action = new int[2];

    private const int SHIFT = 0;
    private const int REDUCE = 1;
    private const int ACCEPT = 2;
    private const int ERROR = 3;

    public Parser(Lexer lexer)
    {
        this.lexer = lexer;
    }

    private int GoTo(int index)
    {
        int state = State();
        int low = 1;
        int high = gotoTable[index].Length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            int middle = (low + high) / 2;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private void Push(int numstate, ArrayList listNode)
    {
        this.nodeList = listNode;

        stack.Push(new State(numstate, this.nodeList));
    }

    private int State()
    {
        State s = (State) stack.Peek();
        return s.state;
    }

    private ArrayList Pop()
    {
        return (ArrayList) ((State) stack.Pop()).nodes;
    }

    private int Index(Switchable token)
    {
        converter.index = -1;
        token.Apply(converter);
        return converter.index;
    }

    public Start Parse()
    {
        Push(0, null);

        IList ign = null;
        while(true)
        {
            while(Index(lexer.Peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new TypedList(NodeCast.Instance);
                }

                ign.Add(lexer.Next());
            }

            if(ign != null)
            {
                ignoredTokens.SetIn(lexer.Peek(), ign);
                ign = null;
            }

            last_pos = lexer.Peek().Pos;
            last_line = lexer.Peek().Line;
            last_token = lexer.Peek();

            int index = Index(lexer.Peek());
            action[0] = actionTable[State()][0][1];
            action[1] = actionTable[State()][0][2];

            int low = 1;
            int high = actionTable[State()].Length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < actionTable[State()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > actionTable[State()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    action[0] = actionTable[State()][middle][1];
                    action[1] = actionTable[State()][middle][2];
                    break;
                }
            }

            switch(action[0])
            {
                case SHIFT:
        {
            ArrayList list = new ArrayList();
            list.Add(lexer.Next());
                        Push(action[1], list);
                        last_shift = action[1];
                    }
        break;
                case REDUCE:
                    switch(action[1])
                    {
                    case 0:
        {
      ArrayList list = New0();
      Push(GoTo(0), list);
        }
        break;
                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) lexer.Next();
                        PFred node1 = (PFred) ((ArrayList)Pop())[0];
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(last_token,
                        "[" + last_line + "," + last_pos + "] " +
                        errorMessages[errors[action[1]]]);
            }
        }
    }

    ArrayList New0()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        TPeriod tperiodNode2 = (TPeriod)nodeArrayList1[0];
        AFred pfredNode1 = new AFred (
              tperiodNode2
        );
        nodeList.Add(pfredNode1);
        return nodeList;
    }

    private static int[][][] actionTable = {
      new int[][] {
        new int[] {-1, 3, 0},
        new int[] {31, 0, 1},
      },
      new int[][] {
        new int[] {-1, 1, 0},
      },
      new int[][] {
        new int[] {-1, 3, 2},
        new int[] {36, 2, -1},
      },
    };

    private static int[][][] gotoTable  = {
      new int[][] {
        new int[] {-1, 2},
      },
    };

    private static String[] errorMessages = {
      "expecting: '.'",
      "expecting: EOF",
    };

    private static int[] errors = {
      0, 1, 1, 
    };
}
}
